__author__ = 'João Gabriel Feres'
__description__ = 'PatMail é um aplicativo para envio automatizado de emails feito totalmente em python, usando para interface gráfica o módulo TKinter.'
__email__ = 'joaogabrielferes@gmail.com'
__license__ = 'MIT'
__project__ = 'PatMail'
__version__ = '0.1.0'